/* eslint-disable perfectionist/sort-enums */
export enum ApiErrorCode {
  UNSPECIFIED_ERROR = 'UNSPECIFIED_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  AUTH_NO_TOKEN = 'AUTH_NO_TOKEN',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_EXISTS = 'AUTH_EMAIL_EXISTS',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_NOT_AUTHENTICATED = 'AUTH_NOT_AUTHENTICATED',

  ACTION_USER_NOT_FOUND = 'ACTION_USER_NOT_FOUND',
}
