-- Migration SQL generated by Prisma + Custom SQL for ticket numbering

-- Create function to fill ticket number
CREATE OR REPLACE FUNCTION fill_ticket_number()
RETURNS TRIGGER AS $$
DECLARE
    next_ticket_number INT;
    prefix_ticket_number TEXT;
BEGIN
    SELECT ticket_prefix_number INTO prefix_ticket_number
    FROM teams
    WHERE id = NEW.team_id;

    IF prefix_ticket_number IS NULL OR prefix_ticket_number = '' THEN
        prefix_ticket_number := 'BRO';
    END IF;

    UPDATE teams 
        SET ticket_last_number = ticket_last_number + 1 
    WHERE id = NEW.team_id 
    RETURNING ticket_last_number INTO next_ticket_number;

    NEW.number := prefix_ticket_number || '-' || next_ticket_number::TEXT;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop trigger
DROP TRIGGER IF EXISTS set_ticket_number ON "tickets";

-- Recreate trigger
CREATE TRIGGER set_ticket_number
BEFORE INSERT ON tickets
FOR EACH ROW
EXECUTE FUNCTION fill_ticket_number();

    
